### ISSUE TITLE
Stop Scan feature

### ISSUE THREAD

**Issue by SarthakJag** [ActivBody/activ5-ble-sample-android#1]
There seems to be a Stop scan feature but it's an internal method. Would be useful it's made public.

**Comment by thironaka** [comment]
Hi SarthakJag,
Thanks for the valuable comment.
We appreciate your insights on this SDK.
We have decided to make this Stop scan feature public in the next SDK.
Thanks again for your interest in the SDK.
Please let me know if you have any other questions/comments.
